const roomTestDate = {
  testRoom1: { players: 2, tilesPlayed: [] },
  testRoom2: { players: 3, tilesPlayed: [] },
  testRoom3: { players: 4, tilesPlayed: [] },
  testRoom4: {
    players: 4,
    tilesPlayed: [
      {
        name: "player1tile14",
        type: "Sprite",
        x: 576,
        y: 384,
        textureKey: "player1",
      },
      {
        name: "player2tile5",
        type: "Sprite",
        x: 608,
        y: 384,
        textureKey: "player2",
      },
      {
        name: "player3tile1",
        type: "Sprite",
        x: 640,
        y: 384,
        textureKey: "player3",
      },
      {
        name: "player4tile9",
        type: "Sprite",
        x: 544,
        y: 384,
        textureKey: "player4",
      },
      {
        name: "player1tile15",
        type: "Sprite",
        x: 576,
        y: 352,
        textureKey: "player1",
      },
      {
        name: "player2tile6",
        type: "Sprite",
        x: 608,
        y: 352,
        textureKey: "player2",
      },
      {
        name: "player3tile0",
        type: "Sprite",
        x: 640,
        y: 352,
        textureKey: "player3",
      },
      {
        name: "player4tile8",
        type: "Sprite",
        x: 544,
        y: 352,
        textureKey: "player4",
      },
      {
        name: "player1tile13",
        type: "Sprite",
        x: 576,
        y: 320,
        textureKey: "player1",
      },
      {
        name: "player2tile4",
        type: "Sprite",
        x: 608,
        y: 320,
        textureKey: "player2",
      },
      {
        name: "player3tile8",
        type: "Sprite",
        x: 640,
        y: 320,
        textureKey: "player3",
      },
      {
        name: "player4tile10",
        type: "Sprite",
        x: 544,
        y: 320,
        textureKey: "player4",
      },
      {
        name: "player1tile12",
        type: "Sprite",
        x: 576,
        y: 288,
        textureKey: "player1",
      },
      {
        name: "player2tile3",
        type: "Sprite",
        x: 608,
        y: 288,
        textureKey: "player2",
      },
      {
        name: "player3tile9",
        type: "Sprite",
        x: 640,
        y: 288,
        textureKey: "player3",
      },
      {
        name: "player4tile0",
        type: "Sprite",
        x: 544,
        y: 288,
        textureKey: "player4",
      },
    ],
  },
};
exports.roomTestDate = roomTestDate;
