const roomTestDate = {
  testRoom1: {
    players: 2,
    tilesPlayed: [],
    assignedPlayers: { player1: null, player2: null },
  },
  testRoom2: {
    players: 3,
    tilesPlayed: [],
    assignedPlayers: { player1: null, player2: null, player3: null },
  },
  testRoom3: {
    players: 4,
    tilesPlayed: [],
    assignedPlayers: {
      player1: null,
      player2: null,
      player3: null,
      player4: null,
    },
  },
  testRoom4: {
    players: 4,
    assignedPlayers: {
      player1: null,
      player2: null,
      player3: null,
      player4: null,
    },
    tilesPlayed: [
      {
        name: "player1tile14",
        type: "Sprite",
        x: 576,
        y: 384,
        textureKey: "player1",
      },
      {
        name: "player2tile5",
        type: "Sprite",
        x: 608,
        y: 384,
        textureKey: "player2",
      },
      {
        name: "player3tile1",
        type: "Sprite",
        x: 640,
        y: 384,
        textureKey: "player3",
      },
      {
        name: "player4tile9",
        type: "Sprite",
        x: 544,
        y: 384,
        textureKey: "player4",
      },
      {
        name: "player1tile15",
        type: "Sprite",
        x: 576,
        y: 352,
        textureKey: "player1",
      },
      {
        name: "player2tile6",
        type: "Sprite",
        x: 608,
        y: 352,
        textureKey: "player2",
      },
      {
        name: "player3tile0",
        type: "Sprite",
        x: 640,
        y: 352,
        textureKey: "player3",
      },
      {
        name: "player4tile8",
        type: "Sprite",
        x: 544,
        y: 352,
        textureKey: "player4",
      },
      {
        name: "player1tile13",
        type: "Sprite",
        x: 576,
        y: 320,
        textureKey: "player1",
      },
      {
        name: "player2tile4",
        type: "Sprite",
        x: 608,
        y: 320,
        textureKey: "player2",
      },
      {
        name: "player3tile8",
        type: "Sprite",
        x: 640,
        y: 320,
        textureKey: "player3",
      },
      {
        name: "player4tile10",
        type: "Sprite",
        x: 544,
        y: 320,
        textureKey: "player4",
      },
      {
        name: "player1tile12",
        type: "Sprite",
        x: 576,
        y: 288,
        textureKey: "player1",
      },
      {
        name: "player2tile3",
        type: "Sprite",
        x: 608,
        y: 288,
        textureKey: "player2",
      },
      {
        name: "player3tile9",
        type: "Sprite",
        x: 640,
        y: 288,
        textureKey: "player3",
      },
      {
        name: "player4tile0",
        type: "Sprite",
        x: 544,
        y: 288,
        textureKey: "player4",
      },
    ],
  },
  testRoom5: {
    players: 4,
    assignedPlayers: {
      player1: null,
      player2: null,
      player3: null,
      player4: null,
    },
    tilesPlayed: [
      {
        name: "player1tile14",
        type: "Sprite",
        x: 576,
        y: 384,
        textureKey: "player1",
      },
      {
        name: "player2tile5",
        type: "Sprite",
        x: 608,
        y: 384,
        textureKey: "player2",
      },
      {
        name: "player3tile1",
        type: "Sprite",
        x: 640,
        y: 384,
        textureKey: "player3",
      },
      {
        name: "player4tile9",
        type: "Sprite",
        x: 544,
        y: 384,
        textureKey: "player4",
      },
      {
        name: "player1tile15",
        type: "Sprite",
        x: 576,
        y: 352,
        textureKey: "player1",
      },
      {
        name: "player2tile6",
        type: "Sprite",
        x: 608,
        y: 352,
        textureKey: "player2",
      },
      {
        name: "player3tile0",
        type: "Sprite",
        x: 640,
        y: 352,
        textureKey: "player3",
      },
      {
        name: "player4tile8",
        type: "Sprite",
        x: 544,
        y: 352,
        textureKey: "player4",
      },
      {
        name: "player1tile13",
        type: "Sprite",
        x: 576,
        y: 320,
        textureKey: "player1",
      },
      {
        name: "player2tile4",
        type: "Sprite",
        x: 608,
        y: 320,
        textureKey: "player2",
      },
      {
        name: "player3tile8",
        type: "Sprite",
        x: 640,
        y: 320,
        textureKey: "player3",
      },
      {
        name: "player4tile10",
        type: "Sprite",
        x: 544,
        y: 320,
        textureKey: "player4",
      },
      {
        name: "player1tile12",
        type: "Sprite",
        x: 576,
        y: 288,
        textureKey: "player1",
      },
      {
        name: "player2tile3",
        type: "Sprite",
        x: 608,
        y: 288,
        textureKey: "player2",
      },
      {
        name: "player3tile9",
        type: "Sprite",
        x: 640,
        y: 288,
        textureKey: "player3",
      },
      {
        name: "player4tile0",
        type: "Sprite",
        x: 544,
        y: 288,
        textureKey: "player4",
      },
      {
        name: "player1tile7",
        type: "Sprite",
        x: 544,
        y: 416,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player1",
        frameKey: 0,
        data: {},
      },
      {
        name: "player2tile7",
        type: "Sprite",
        x: 576,
        y: 416,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player2",
        frameKey: 0,
        data: {},
      },
      {
        name: "player3tile2",
        type: "Sprite",
        x: 608,
        y: 416,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player3",
        frameKey: 0,
        data: {},
      },
      {
        name: "player4tile1",
        type: "Sprite",
        x: 640,
        y: 416,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player4",
        frameKey: 0,
        data: {},
      },
      {
        name: "player1tile6",
        type: "Sprite",
        x: 544,
        y: 448,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player1",
        frameKey: 0,
        data: {},
      },
      {
        name: "player2tile15",
        type: "Sprite",
        x: 576,
        y: 448,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player2",
        frameKey: 0,
        data: {},
      },
      {
        name: "player3tile10",
        type: "Sprite",
        x: 608,
        y: 448,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player3",
        frameKey: 0,
        data: {},
      },
      {
        name: "player4tile2",
        type: "Sprite",
        x: 640,
        y: 448,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player4",
        frameKey: 0,
        data: {},
      },
      {
        name: "player1tile5",
        type: "Sprite",
        x: 544,
        y: 480,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player1",
        frameKey: 0,
        data: {},
      },
      {
        name: "player2tile14",
        type: "Sprite",
        x: 608,
        y: 480,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player2",
        frameKey: 0,
        data: {},
      },
      {
        name: "player3tile3",
        type: "Sprite",
        x: 576,
        y: 480,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player3",
        frameKey: 0,
        data: {},
      },
      {
        name: "player4tile11",
        type: "Sprite",
        x: 640,
        y: 480,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player4",
        frameKey: 0,
        data: {},
      },
      {
        name: "player1tile4",
        type: "Sprite",
        x: 544,
        y: 512,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player1",
        frameKey: 0,
        data: {},
      },
      {
        name: "player2tile13",
        type: "Sprite",
        x: 608,
        y: 512,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player2",
        frameKey: 0,
        data: {},
      },
      {
        name: "player3tile11",
        type: "Sprite",
        x: 576,
        y: 512,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player3",
        frameKey: 0,
        data: {},
      },
      {
        name: "player4tile3",
        type: "Sprite",
        x: 640,
        y: 512,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player4",
        frameKey: 0,
        data: {},
      },
      {
        name: "player1tile11",
        type: "Sprite",
        x: 640,
        y: 544,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player1",
        frameKey: 0,
        data: {},
      },
      {
        name: "player2tile12",
        type: "Sprite",
        x: 608,
        y: 544,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player2",
        frameKey: 0,
        data: {},
      },
      {
        name: "player3tile4",
        type: "Sprite",
        x: 576,
        y: 544,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player3",
        frameKey: 0,
        data: {},
      },
      {
        name: "player4tile12",
        type: "Sprite",
        x: 544,
        y: 544,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player4",
        frameKey: 0,
        data: {},
      },
      {
        name: "player1tile3",
        type: "Sprite",
        x: 640,
        y: 576,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player1",
        frameKey: 0,
        data: {},
      },
      {
        name: "player2tile11",
        type: "Sprite",
        x: 608,
        y: 576,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player2",
        frameKey: 0,
        data: {},
      },
      {
        name: "player3tile12",
        type: "Sprite",
        x: 576,
        y: 576,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player3",
        frameKey: 0,
        data: {},
      },
      {
        name: "player4tile4",
        type: "Sprite",
        x: 544,
        y: 576,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player4",
        frameKey: 0,
        data: {},
      },
      {
        name: "player1tile10",
        type: "Sprite",
        x: 544,
        y: 256,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player1",
        frameKey: 0,
        data: {},
      },
      {
        name: "player2tile2",
        type: "Sprite",
        x: 576,
        y: 256,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player2",
        frameKey: 0,
        data: {},
      },
      {
        name: "player3tile5",
        type: "Sprite",
        x: 608,
        y: 256,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player3",
        frameKey: 0,
        data: {},
      },
      {
        name: "player4tile5",
        type: "Sprite",
        x: 640,
        y: 256,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player4",
        frameKey: 0,
        data: {},
      },
      {
        name: "player1tile2",
        type: "Sprite",
        x: 544,
        y: 224,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player1",
        frameKey: 0,
        data: {},
      },
      {
        name: "player2tile1",
        type: "Sprite",
        x: 576,
        y: 224,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player2",
        frameKey: 0,
        data: {},
      },
      {
        name: "player3tile13",
        type: "Sprite",
        x: 608,
        y: 224,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player3",
        frameKey: 0,
        data: {},
      },
      {
        name: "player4tile13",
        type: "Sprite",
        x: 640,
        y: 224,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player4",
        frameKey: 0,
        data: {},
      },
      {
        name: "player1tile9",
        type: "Sprite",
        x: 544,
        y: 192,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player1",
        frameKey: 0,
        data: {},
      },
      {
        name: "player2tile0",
        type: "Sprite",
        x: 576,
        y: 192,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player2",
        frameKey: 0,
        data: {},
      },
      {
        name: "player3tile6",
        type: "Sprite",
        x: 608,
        y: 192,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player3",
        frameKey: 0,
        data: {},
      },
      {
        name: "player4tile14",
        type: "Sprite",
        x: 640,
        y: 192,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player4",
        frameKey: 0,
        data: {},
      },
      {
        name: "player1tile1",
        type: "Sprite",
        x: 544,
        y: 160,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player1",
        frameKey: 0,
        data: {},
      },
      {
        name: "player2tile10",
        type: "Sprite",
        x: 576,
        y: 160,
        depth: 1,
        scale: [Object],
        origin: [Object],
        flipX: false,
        flipY: false,
        rotation: 0,
        alpha: 1,
        visible: true,
        blendMode: 0,
        textureKey: "player2",
        frameKey: 0,
        data: {},
      },
    ],
  },
};
exports.roomTestDate = roomTestDate;
